{% set name = "diamond" %}
{% set version = "0.9.20" %}
{% set sha256 = "5cf629baf135f54dc93728e3618ae08c64c1ecb81b3f2d2d48fcfd1c010ed8f0" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/bbuchfink/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: False

requirements:
  build:
    - gcc  # [unix]
    - llvm  # [osx]
    - cmake
    - zlib {{ CONDA_ZLIB }}*
  run:
    - libgcc  # [unix]
    - zlib {{ CONDA_ZLIB }}*

test:
  commands:
    - diamond --help 2>&1 > /dev/null

about:
  home: https://github.com/bbuchfink/diamond
  license: AGPL
  summary: Accelerated BLAST compatible local sequence aligner
