{% set name = "livekraken" %}
{% set version = "1.0" %}
{% set sha256 = "6bc2892ef330863fda15d06f349ad85a68c4c8266bb110e5d85ed50b933f5329" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://gitlab.com/rki_bioinformatics/LiveKraken/-/archive/master/LiveKraken-master.tar.gz

  sha256: {{ sha256 }}

build:
  number: 1
  has_prefix_files:
    - libexec/kraken
    - libexec/kraken-build
    - libexec/kraken-filter
    - libexec/kraken-mpa-report
    - libexec/kraken-report
    - libexec/kraken-translate

requirements:
  build:
    - perl
    - gcc
    - boost 

  run:
    - jellyfish 1.*
    - perl
    - libgcc

test:
  commands:
    - kraken --version
    - kraken-build --version
    - kraken-filter --version
    - kraken-mpa-report --version
    - kraken-report --version
    - kraken-translate --version

about:
  home: https://gitlab.com/SimonHTausch/LiveKraken
  license: GPLv3
  license_file: LICENSE
  summary: LiveKraken is a real-time metagenomic classifier for Illumina sequencing data.
