{% set pkgname = "gretel" %}
{% set cmdname = "gretel" %}
{% set version = "0.0.93" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

build:
  number: 0
  noarch: python

source:
  url: https://github.com/SamStudio8/{{ pkgname }}/archive/v{{ version }}.tar.gz
  sha256: f45f898aa882a83db087358865a674e62dc194afeef8324c9225284a399998f0

requirements:
  host:
    - python
    - setuptools
  run:
    - python <3
    - pysam
    - numpy
    - hanselx=0.0.92
    - pyvcf

test:
  commands:
    - {{ cmdname }} -h
    - {{ cmdname }} --version | grep '{{ version }}'
  imports:
    - {{ cmdname }}

about:
  home: https://github.com/SamStudio8/{{ pkgname }}
  license: MIT
  license_file: LICENSE
  summary: 'An algorithm for recovering haplotypes from metagenomes'

extra:
  identifiers:
    - doi:10.1101/223404
