{% set version = '0.1.14' %}

package:
  name: r-sigqc
  version: {{ version|replace("-", "_") }}

source:
  fn: sigQC_0.1.14.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/sigQC_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/sigQC/sigQC_{{ version }}.tar.gz
  sha256: 90678a5e52eb0813efaf32f6c225fef7c73fe5ddbcf8dadd5be321bbe6756f9f

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown
requirements:
  build:
    - r-base
    - bioconductor-complexheatmap
    - r-kernsmooth
    - r-mass
    - bioconductor-rankprod
    - r-biclust
    - r-class
    - r-cluster
    - r-fmsb
    - r-gplots
    - r-gridgraphics
    - r-lattice
    - r-mclust
    - r-moments
    - r-nnet

  run:
    - r-base
    - bioconductor-complexheatmap
    - r-kernsmooth
    - r-mass
    - bioconductor-rankprod
    - r-biclust
    - r-class
    - r-cluster
    - r-fmsb
    - r-gplots
    - r-gridgraphics
    - r-lattice
    - r-mclust
    - r-moments
    - r-nnet

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('sigQC')"           # [not win]
    - "\"%R%\" -e \"library('sigQC')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=sigQC
  license: file LICENSE (Restricts use)
  summary: Provides gene signature quality control metrics in publication ready plots. Namely,
    enables the visualization of properties such as expression, variability, correlation,
    and comparison of methods of standardisation and scoring metrics.
  license_family: OTHER

# The original CRAN metadata for this package was:

# Package: sigQC
# Title: Quality Control Metrics for Gene Signatures
# Version: 0.1.14
# Authors@R: c(person(given = "Andrew", family = "Dhawan", email="andrew.dhawan@oncology.ox.ac.uk", role = c("aut")), person(given = "Alessandro", family = "Barberis", email="alessandro.barberis@oncology.ox.ac.uk", role = c("aut")), person(given = "Wei-Chen", family = "Cheng", email="wei-chen.cheng@oncology.ox.ac.uk", role = c("aut")), person(given = "Francesca", family = "Buffa", email="francesca.buffa@oncology.ox.ac.uk", role = c("aut","cre")))
# Description: Provides gene signature quality control metrics in publication ready plots. Namely, enables the visualization of properties such as expression, variability, correlation, and comparison of methods of standardisation and scoring metrics.
# Depends: R (>= 3.3.0)
# License: file LICENSE
# License_restricts_use: yes
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.0.1
# Imports: MASS, lattice, KernSmooth, cluster, nnet, class, gridGraphics, biclust, gplots, ComplexHeatmap, RankProd, fmsb, moments, grDevices, graphics, stats, utils, mclust
# Suggests: knitr, rmarkdown
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2018-03-26 11:26:42 UTC; dhawana
# Author: Andrew Dhawan [aut], Alessandro Barberis [aut], Wei-Chen Cheng [aut], Francesca Buffa [aut, cre]
# Maintainer: Francesca Buffa <francesca.buffa@oncology.ox.ac.uk>
# Repository: CRAN
# Date/Publication: 2018-04-11 14:40:09 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
