{% set version = '1.2.0' %}

package:
  name: r-biclust
  version: {{ version|replace("-", "_") }}

source:
  fn: biclust_1.2.0.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/biclust_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/biclust/biclust_{{ version }}.tar.gz
  sha256: af2d9f9b5dda8117f686af47b217450184c6a0ba69ff27f6fa84b671ff91730f

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: isa2
requirements:



  build:
    - r-base
    - r-mass
    - r-colorspace
    - r-flexclust
    - r-lattice

  run:
    - r-base
    - r-mass
    - r-colorspace
    - r-flexclust
    - r-lattice

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('biclust')"           # [not win]
    - "\"%R%\" -e \"library('biclust')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=biclust
  license: GPL-3
  summary: 'The main function biclust provides several algorithms to find biclusters in two-dimensional
    data: Cheng and Church, Spectral, Plaid Model, Xmotifs and Bimax. In addition, the
    package provides methods for data preprocessing (normalization and discretisation),
    visualisation, and validation of bicluster solutions.'

  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: biclust
# Version: 1.2.0
# Date: 2015-05-08
# Author: Sebastian Kaiser, Rodrigo Santamaria, Tatsiana Khamiakova, Martin Sill, Roberto Theron, Luis Quintales, Friedrich Leisch and Ewoud De Troyer.
# Maintainer: Sebastian Kaiser <Sebastian.Kaiser@stat.uni-muenchen.de>
# Title: BiCluster Algorithms
# Depends: R (>= 2.10), MASS, grid, colorspace, lattice
# Imports: methods, flexclust
# Suggests: isa2
# Description: The main function biclust provides several algorithms to find biclusters in two-dimensional data: Cheng and Church, Spectral, Plaid Model, Xmotifs and Bimax. In addition, the package provides methods for data preprocessing (normalization and discretisation), visualisation, and validation of bicluster solutions.
# License: GPL-3
# LazyLoad: yes
# Repository: CRAN
# Repository/R-Forge/Project: biclust
# Repository/R-Forge/Revision: 225
# Date/Publication: 2015-05-12 11:44:19
# NeedsCompilation: yes
# Repository/R-Forge/DateTimeStamp: 2015-05-08 13:40:16
# Packaged: 2015-05-11 20:10:09 UTC; rforge

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
