{% set version = '0.6.3' %}

package:
  name: r-fmsb
  version: {{ version|replace("-", "_") }}

source:
  fn: fmsb_0.6.3.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/fmsb_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/fmsb/fmsb_{{ version }}.tar.gz
  sha256: 4503998d2fd90f5ee62587594dc2adeaf022355d2e294dc5bcfb0271bd5d49d8

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - gcc  # [linux]
    - llvm # [osx]

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('fmsb')"           # [not win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://minato.sip21c.org/msb/
  license: GPL (>= 2)
  summary: Several utility functions for the book entitled  "Practices of Medical and Health
    Data Analysis using R" (Pearson Education Japan, 2007) with Japanese demographic
    data and some demographic analysis related functions.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: fmsb
# Version: 0.6.3
# Date: 2018-04-2
# Title: Functions for Medical Statistics Book with some Demographic Data
# Author: Minato Nakazawa <minato-nakazawa@umin.net>
# Maintainer: Minato Nakazawa <minato-nakazawa@umin.net>
# Depends: R (>= 2.2.0)
# Description: Several utility functions for the book entitled  "Practices of Medical and Health Data Analysis using R" (Pearson Education Japan, 2007) with Japanese demographic data and some demographic analysis related functions.
# License: GPL (>= 2)
# URL: http://minato.sip21c.org/msb/
# NeedsCompilation: no
# Packaged: 2018-04-03 10:03:30 UTC; Minato
# Repository: CRAN
# Date/Publication: 2018-04-03 21:37:31 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
